### ISSUE TITLE
Image paths are hard-coded

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr-tutorial#1]
Some of the image paths are hard-coded, which makes it impossible to version them. In particular:

```
tutorial/src/cost_sensitive_classif.Rmd:![theoretic threshold](../../../images/theoretic_threshold.png "theoretic threshold")
tutorial/src/cost_sensitive_classif.Rmd:![weight positive](../../../images/weight_positive.png "weight positive")
tutorial/src/cost_sensitive_classif.Rmd:![theoretic weight positive](../../../images/theoretic_weight_positive.png "theoretic weight positive")
tutorial/src/resample.Rmd:![Resampling Figure](../../../images/resampling.png "Resampling Figure")
```

**Comment by jakob-r** [comment]
I am on this now. But I can't find any of these links anymore except the resampling one. (and the logo in the css)

**Comment by jakob-r** [comment]
My solution now was to create a symlink in `tutorial/custom_theme/img` for the pictures we actually use from `images/`.
When the tutorial is build it will include the _real_ pictures so they won't change until we build it again. They will be also included in the zip correctly.

**Comment by larskotthoff** [comment]
Thanks, sounds good. The build is failing at the moment tough saying that it can't find an image file, see https://travis-ci.org/mlr-org/mlr-tutorial/builds/68456413 (I've just added you to the Travis notifications).

**Comment by schiffner** [comment]
I had a look today and could reproduce the error on my system. For some reason in both symlinks the paths to the files in `images/` ended with a `?` (which don't show up in the files/diffs displayed by Github). After removing them building the tutorial worked fine for me.
The travis job gives a 50 min error at the moment.

**Comment by larskotthoff** [comment]
I started it again and it just finished. Looks like everything's working now, thanks!

**Comment by schiffner** [comment]
Thanks, Jakob and Lars.
