### ISSUE TITLE
Speeding up Travis

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#10]
Travis runs into timeouts fairly often.

I think there is a lot of potential in making things cheaper in the R code of the tutorial. I can go over it next week.

But as one some occasions cheap examples do not make sense we should also think about other means.  
- We could pre-generate more expensive objects like an example `BenchmarkResult`, similar to the `Task`s we already have. I'm not really a fan of this option, though.
- The whole setup/installation process takes a long time, mostly 35-40 min. But I've also seen Travis builds where the installation alone exceeded 50 min. We could maybe cache some of the dependencies?

**Comment by berndbischl** [comment]
Do you use Michels trick in travis to use binaries?

**Comment by schiffner** [comment]
No, thanks for reminding me about that.

**Comment by berndbischl** [comment]
You need to copy that from the yml. that will save you like 20 mins

**Comment by schiffner** [comment]
Ok. We should probably do that next week to avoid breaking things again.

**Comment by berndbischl** [comment]
If you look at it carefully, you could try now. Because Michel and I will also work mlr stuff on Friday

**Comment by larskotthoff** [comment]
It's not that easy because the tutorial build can't use the travis R machinery. I wouldn't do it now.

**Comment by schiffner** [comment]
I don't really understand. Why not? What do you mean by 'the travis R machinery'?

**Comment by larskotthoff** [comment]
When you tell Travis that you're building an R package, it automatically does things like install dependencies and binary packages as specified in the mlr travis file. For the tutorial, we're telling it that it's a bash build and run everything to install dependencies manually (this is necessary because R builds assume an R package and don't work for the tutorial).

So in order to make the binary packages stuff work, we need to replicate whatever Travis does for R builds to install them. This shouldn't be too hard, but it's not a direct porting over of the changes to the mlr build.

**Comment by schiffner** [comment]
I see, thanks.

**Comment by berndbischl** [comment]
I just looked at the yml. I guess we can do something very similar here.
But maybe @mllg  should do this, he has the most experience with the binary install, and there were some problems in the mlr repo and it took him some time to figure out how to do this.

Michel?

**Comment by larskotthoff** [comment]
I've configured the Travis build to install packages in parallel and that saves us about 10-15 minutes. With that, it fits comfortably into the 50 minutes. I'm closing this for now.

**Comment by berndbischl** [comment]
Can this be used for normal mlr as well?

**Comment by larskotthoff** [comment]
It doesn't look like it. For mlr, Travis handles installing packages and dependencies and as far as I can see, there's no way to tell that to run in parallel.

**Comment by berndbischl** [comment]
so we should open up a issue at rtravis and tell them about it? if it is principle possible?
or do i misundersstand  what happens?

**Comment by larskotthoff** [comment]
In principle all you need to do is add `Ncpus = x` to `install.packages()`. So yes, this should certainly be possible. I'll open an issue.

**Comment by berndbischl** [comment]
great thx

**Comment by larskotthoff** [comment]
Opened travis-ci/travis-ci#4202.
