### ISSUE TITLE
Build fail on local

### ISSUE THREAD

**Issue by SteveBronder** [mlr-org/mlr-tutorial#104]
I'm trying to do `./build` on the current docs and am getting the error
```
Knitting file 'bagging.Rmd' ...
Quitting from lines 64-71 () 
Error in train.default(learner = bag.lrn, task = bh.task, subset = train.inds) : 
  argument "y" is missing, with no default
Calls: lapply ... withVisible -> eval -> eval -> train -> train.default
Execution halted
```

**Comment by SteveBronder** [comment]
Odd, I think it is trying to run carets train function?

**Comment by SteveBronder** [comment]
Looking at `./build` this appears to have been an issue before. On line 111

```r
  library(caret) # we get problems if this shadows "mlr::train"
```

**Comment by SteveBronder** [comment]
Resolved in the short term

If you have mlr loading automatically in your Rprofile then it will load before caret is loaded, causing caret's `train` to be called first

Is there a way in build to set the `--vanilla` option for Rscript?

**Comment by berndbischl** [comment]
> If you have mlr loading automatically in your Rprofile then it will load before caret is loaded, causing caret's train to be called f

yes, thats correct. i am not sure what to do against this  except for removing mlr from your Rprofile.
i usually just load very smallish helper packages in my Rprofile.
