### ISSUE TITLE
Write a page about dummy learners

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#108]

**Comment by pat-s** [comment]
Not sure if this is so important - can someone give me a headsup on this? Maybe @jakob-r?

**Comment by jakob-r** [comment]
I guess `featureless` Learners are meant? Should be mentioned somewhere. I note it down for the whyr mlr hackathon

**Comment by pat-s** [comment]
This issue was moved to mlr-org/mlr#2315
