### ISSUE TITLE
Best score for G2 metric should equal 1

### ISSUE THREAD

**Issue by alvinthai** [mlr-org/mlr-tutorial#122]
https://github.com/mlr-org/mlr-tutorial/blob/76157380287fca598a4e564c3e700386e7ff734a/devel/html/measures/index.html#L1181

according to the definition:
(number of concordant comparisons - number of discordant comparisons) / (number of concordant comparisons + number of discordant comparisons)

the limit for best score should be 1 (number of discordant comparisons = 0)

**Comment by jakob-r** [comment]
Following the logic of this formula I guess you are right. Maybe @larskotthoff knows something more. Probably a copy & paste error of the G1 index?

**Comment by larskotthoff** [comment]
Yep, that's a typo. I'll fix this.
