### ISSUE TITLE
Example of trafo for sigma tuning in kernlab

### ISSUE THREAD

**Issue by MinhAnhL** [mlr-org/mlr-tutorial#124]
The example of specifying the search space of the sigma parameter in kernlab might be not correct. I talked to Bernd, the basis of the trafo should be 2 and not 10 (same for the C param?).

> makeNumericParam("sigma", lower = -10, upper = 10, trafo = function(x) 10^x)

should be

> makeNumericParam("sigma", lower = -12, upper = 12, trafo = function(x) 2^x)

http://mlr-org.github.io/mlr-tutorial/devel/html/tune/index.html

**Comment by jakob-r** [comment]
indeed.
