### ISSUE TITLE
default branch: gh-pages:

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr-tutorial#126]
Can I set the default branch to gh-pages [here](https://github.com/mlr-org/mlr-tutorial/settings/branches) or can we move everything to the master branch as github allows it now to be the source for the gh-page.

Thoughts, fears etc.?

**Comment by pat-s** [comment]
I had similar thoughts some time ago but forgot to write it down :+1:

**Comment by pat-s** [comment]
@jakob-r do it then?

**Comment by jakob-r** [comment]
Done. Please tell me if something behaves strangely.
