### ISSUE TITLE
Basics/Benchmark: Color coding

### ISSUE THREAD

**Issue by MiGraber** [mlr-org/mlr-tutorial#128]
[Benchmark Color coding](https://mlr-org.github.io/mlr-tutorial/release/html/benchmark_experiments/index.html#benchmark-analysis-and-visualization)
The color coding of "rf" and "rpart" alternate, which is quite a bit confusing.

**Comment by MiGraber** [comment]
For most of the graphs you can force the right coding with the argument:
`order.lrn = getBMRLearnerIds(bmr)`
but some plotting functions dont have this argument, so I do not know if it is possible to force the right coding there, but I dont know if this is important since most graphs are right.
```
plotBMRSummary()
plotCritDifferences()
qplot()
```
https://github.com/mlr-org/mlr-tutorial/pull/130

**Comment by pat-s** [comment]
See https://github.com/mlr-org/mlr/pull/2297.

Thanks for the work! I finished it up and opened a new PR in the main repo since this one is deprecated.
