### ISSUE TITLE
Usage of undefined term "eol" in hyperpar_tuning_effects

### ISSUE THREAD

**Issue by AlexEngelhardt** [mlr-org/mlr-tutorial#137]
In hyperpar_tuning_effects.Rmd, this sentence appears:

> The include.diagnostics argument will tell [%mlr] whether to include the eol and any error messages

I can't figure out what "eol" means, and it's not mentioned again in this document. What does it mean, and does it make sense to write it out (if it's an acronym)?

**Comment by jakob-r** [comment]
end of life... but you are right it's really underdocumented (as it is a part of ParamHelpers).
Is it even used by mlr?

**Comment by pat-s** [comment]
This issue was moved to mlr-org/mlr#2301
