### ISSUE TITLE
Travis and mlr dependencies

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#14]
If dependencies are added to mlr devel the Travis build of the tutorial can break due to uninstalled packages (today this happened because of the new learners from `neuralnet` and `SwarmSVM`).

**Comment by berndbischl** [comment]
Ok. This is kinda hard to automise. So I guess you need to watch this a bit :(
But should be easy to figure out and see if it happens

**Comment by schiffner** [comment]
I simply told Travis to also install the dependencies for the github version of mlr. So this exact problem should hopefully never happen again. :)
