### ISSUE TITLE
partial_dependence broken

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr-tutorial#141]
by this commit: https://github.com/mlr-org/mlr/commit/f09ee72135ef6618bbdb4eaab1b8e979f71fb65b
because the `centering` option was removed?

```r
iris = getTaskData(iris.task)
pd.ind.classif = generatePartialDependenceData(fit.classif, iris.task, "Petal.Length", individual = TRUE,
  center = list("Petal.Length" = min(iris$Petal.Length)))

Error in (function (data, vars, n, model, uniform = TRUE, points, int.points, : unused argument (center = list(Petal.Length = 1))
```

**Comment by pat-s** [comment]
@zmjones cc @larskotthoff 

The tutorial section on partial dependence is broken due to the commit in mlr referenced above. Could you please fix it? :) It blocks the travis build.

**Comment by zmjones** [comment]
yep i am working on it now
