### ISSUE TITLE
show how to do normal cost-sens classification with mlr

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr-tutorial#15]
See mlr-org/mlr#114

show an example application with
- binary classes
- multi-classes

then extend later

Two things can be added to the tutorial:
- Use methods for example-dependent costs for "normal" class-dependent cost problems. (I have to think this through first.)
- Push the function (we talked about some time ago) that calculates the expected costs and selects the cheapest class to mlr and then add an example to the tutorial.

One could also mention cost curves (via plotROCRCurves, ViperCharts).

**Comment by berndbischl** [comment]
here is also a issue thread about this #821

and one should probably also search the mlr issue tracker. this topic came up multiple times.

**Comment by pat-s** [comment]
This seems to be implemented in the tutorial already, so I'll close.
