### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#24]
At the moment the html pages are not pushed because

```
git push
fatal: unable to access 'https://httpshub.com/mlr-org/mlr-tutorial.git/': Couldn't resolve host 'httpshub.com'
```

**Comment by schiffner** [comment]
Apparently something changed in Travis (?) and the remote.origin.url started already with https.
Just had to delete this line

```
- git remote set-url --push origin $(git config remote.origin.url | sed -e 's/git/https/')
```

**Comment by larskotthoff** [comment]
Thanks for fixing this. Working with Travis is a bit of a pain...

**Comment by schiffner** [comment]
You're welcome. As you're constantly battling Travis, I thought I could share at least a bit of the pain. But fortunately, it was an easy fix.
