### ISSUE TITLE
Automatic link checking

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#25]
Relevant info from https://github.com/mlr-org/mlr/issues/157:
- automatic link checking: try http://wummel.github.io/linkchecker/
- Autodidact24 also proposed: https://github.com/endymion/link-checker
  Its a Ruby gem and works well static HTML pages.

Also from Autodidact24: So, we use Travis CI for testing the project. If we decide to use http://wummel.github.io/linkchecker/, which is a Python framework, we'll just put something like this in .travis.yml:

```
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
script: python tests/link_checker.py
branches:
  only:
    - gh-pages
```

**Comment by pat-s** [comment]
This issue was moved to mlr-org/mlr#2300
