### ISSUE TITLE
mini issue: please add 1 sentence in the learner API

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr-tutorial#26]
Dependent parameters with a \code{requires} field must use \code{quote} and not
   \code{expression} to define it.

**Comment by schiffner** [comment]
Yep, will do.
Added it to my todo-list when I saw Lars' PR.

**Comment by berndbischl** [comment]
@schiffner 
this issues seems to be about 1 sentence. can you do this then close?

**Comment by pat-s** [comment]
This issue was moved to mlr-org/mlr#2327
