### ISSUE TITLE
Make the tutorial build faster

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr-tutorial#27]
1. Use binary R packages instead of installing everything from source.
2. Measure how long each part of the tutorial takes to compile to see where we could save something.

**Comment by larskotthoff** [comment]
1 is done and sped everything up by more than 15 minutes, so we're good for now.

2 can wait.

**Comment by schiffner** [comment]
Thx. That's pretty cool.

**Comment by berndbischl** [comment]
thx +1!

**Comment by berndbischl** [comment]
swell i made the suggestion and forced him to do it, lars still wants a better CI :)
(still very good)

**Comment by larskotthoff** [comment]
And then he forced me to do his shopping as well!

**Comment by schiffner** [comment]
I see... Definitely first steps to the dark side...
