### ISSUE TITLE
feature selection

### ISSUE THREAD

**Issue by zmjones** [mlr-org/mlr-tutorial#3]
with the head copy of mlr i have an error in 109 of `filter_features.Rmd`. 

``` r
> lrn = makeFilterWrapper(learner = "classif.fnn", fw.method = "information.gain", fw.abs = 2)
> rdesc = makeResampleDesc("CV", iters = 10)
> r = resample(learner = lrn, task = iris.task, resampling = rdesc, show.info = FALSE, models = TRUE)
Error in resample(learner = lrn, task = iris.task, resampling = rdesc,  : 
  Assertion on 'xs' failed: Must be of type 'list', not 'NULL'
```

**Comment by larskotthoff** [comment]
Are you running the Github version of ParamHelpers?

**Comment by zmjones** [comment]
nope that was it.  made this mistake before arg!

unrelated quick question. i am writing a page for the partial prediction stuff which is only in devel. how do i do that in the tutorial? i looked at the structure and didn't see the obvious way.

**Comment by larskotthoff** [comment]
Not sure what you mean -- you can either add to an existing page or create a new one. The navigation links etc are generated automatically.

**Comment by zmjones** [comment]
right. what i am confused about is the versioning. some functions arguments changed from 2.4 to devel and i don't see from the travis file how that is dealt with.

**Comment by larskotthoff** [comment]
The old versions are generated manually and static. Any changes you make will show up in the devel version and eventually in new releases once those are archived. The travis job only regenerates the current version.

**Comment by zmjones** [comment]
ah ok. that makes sense now

**Comment by zmjones** [comment]
apparently some weirdness resulted in `feature_selection.Rmd` building, but the same error is there again now. github version of paramhelpers now.

**Comment by larskotthoff** [comment]
Hmm, but this works in Travis, right? Have you checked that you have installed all packages the same way as in Travis?

**Comment by zmjones** [comment]
I guess maybe it could be something changed in mlr since the last tutorial rebuild?

**Comment by zmjones** [comment]
yea i essentially re-ran the travis script locally.

**Comment by larskotthoff** [comment]
The last mlr commit is before the last Travis run. I'll rerun the last build to check.

**Comment by zmjones** [comment]
ok thanks. very frustrating!

**Comment by larskotthoff** [comment]
It may also help if you remove the cache.

**Comment by zmjones** [comment]
yea i have done that each time now

**Comment by larskotthoff** [comment]
Works fine for me locally. It's been a while since I've updated all my packages.

**Comment by zmjones** [comment]
I am currently going with the nuclear option and reinstalling all my packages. I have been trying to get this to work for waaay too long.

**Comment by zmjones** [comment]
reinstalled everything on my system and it is the same error. including removing the cache and following the travis install order. same error thrown interactively

**Comment by larskotthoff** [comment]
Ok, it's fine on travis. Sounds like it's your R installation? Maybe if you update that?

**Comment by zmjones** [comment]
ugh. yea that is what started all this.
