### ISSUE TITLE
rdocumentation still on 2.2

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#30]
We talked about this briefly some time ago in this [mega thread](https://github.com/mlr-org/mlr/issues/330). The docs of mlr on rdocumentation are still for version 2.2.
Meanwhile, many help pages are outdated and there are whole tutorial pages with the majority of links broken (like visualization or benchmark experiments).

I personally find this annoying. On the other hand, nobody has complained yet.

Does anyone know of an alternative platform?
I checked but couldn't find anything (inside-R for example is on mlr version 1.something).

We could generate the docs ourselves. Possibilities are:
- just use utils::Rd2HTML
- knitr::knit_rd
- The staticdocs package https://github.com/hadley/staticdocs (I tried this shortly, but gave up as /cr in other sections than @param causes errors.)

**Comment by zmjones** [comment]
Looks like [this](http://rpackages.ianhowson.com/cran/mlr/) might work.

**Comment by berndbischl** [comment]
this is really annoying as rendering to html should be really easy.
i tried staticdocs before and we once had html online help pages for mlr that worked. 
but what you are saying does not sound very reassuring.

**Comment by berndbischl** [comment]
@zmjones 
Nice find. So it would be an easy URL change to use this? And we just pray that they dont dissapear like rdocumentation.org?

**Comment by schiffner** [comment]
@zmjones: Thanks, hadn't found this.

**Comment by mllg** [comment]
There is also https://github.com/hadley/staticdocs and http://www.inside-r.org/packages/.

Inside-R might be sufficient if we can keep up a frequent release cycle, otherwise we should provide additional documentation via staticdocs for the development version.

**Comment by berndbischl** [comment]
@mllg 
Julia already said staticdocs did not work for her (with mlr)?

And we also looked at inside-r before. And if we need staticdocs on top of it it also isnt a (reliable?) option?

**Comment by berndbischl** [comment]
Just to be clear, I would love staticdocs to work. But I am really annoyed at this, twofold. 
a) We invested lots of work into this already
b) It still sucks.

**Comment by berndbischl** [comment]
or better b) = we kinda need this for the tutorial, and all the links are broken, which is why it sucks.

**Comment by schiffner** [comment]
So I checked out Zach's find. It looks like they have everything but the mandatory packages like base, stats, etc.

Thanks Michel.
I could swear that last week mlr on inside-r was on version 1.18 or something like this... 

How much work did you invest in staticdocs already? Did it work?
My only problem with staticdocs and mlr were errors caused by some of the /cr.
I tried it with some of my own packages and that went well.

**Comment by mllg** [comment]
I'll push some doc fixes in a few minutes.

**Comment by mllg** [comment]
With these fixes you should be able to compile most pages to html with `build_site()`, I still had trouble with the index though.

https://github.com/mlr-org/mlr/pull/583

**Comment by schiffner** [comment]
@mllg: Thank you very much.

Where do you think should I put the html docs? mlr, mlr-tutorial, own repo?

**Comment by mllg** [comment]
IMHO a repository "mlr-help" would be neat.

**Comment by berndbischl** [comment]
> Where do you think should I put the html docs? mlr, mlr-tutorial, own repo?

We are going to create them once per CRAN release, arent we?
I might vote for extra repo.

**Comment by mllg** [comment]
Has anyone tried knitr yet? http://yihui.name/en/2012/10/build-static-html-help/

**Comment by mllg** [comment]
Well, I think knitr cannot handle external links until you compile all installed packages... Forget about it.

**Comment by schiffner** [comment]
Only for like 5 mins. I had the same problem and didn't look further.

**Comment by schiffner** [comment]
Only for completeness: (As inside-r) http://www.crantastic.org/packages/mlr is also up to date now and also has docs for older mlr versions.

**Comment by schiffner** [comment]
Forget what I said about crantastic. They don't have docs.

Both inside-r and http://rpackages.ianhowson.com have mlr 2.7 docs

inside-r: 
- has docs for base packages
- many docs are outdated (for example the docs for party are over 2 years old)
- no links between doc pages (only to base and recommended packages)

http://rpackages.ianhowson.com
- does not have docs for base packages
- up to date as far as I checked
- no links between doc pages

I pushed a tutorial version where I link to http://rpackages.ianhowson.com for contributed and recommended packages and inside-r for base packages (inside-r seems more up-to-date for these packages than rdocumentation) and changed everything such that we can easily switch between platforms (or our own docs if we generate them ourselves).

c8f28b0a07c07b9d4aa846b13eaad9323ecaeb23

**Comment by berndbischl** [comment]
> does not have docs for base packages

who cares.

> up to date as far as I checked

sounds good! I guess this is most relevant.

**Comment by berndbischl** [comment]
hmm, ok so i see you also dont need my comments as you are already finishing a good compromise? 
hopefully it is not too much work

**Comment by schiffner** [comment]
It was a bit of work, that's why I procrastinated this long...
You can look at the devel-version of the tutorial and see if you like.

**Comment by berndbischl** [comment]
I looked at it quickly but it is just more working links, to the ianhowson page now?
So I guess there is nothing to dislike? Or check?

**Comment by schiffner** [comment]
Yep. Not much to see or check. Just wanted to keep you all informed and give you the opportunity for any kind of protest/suggestions. :)

**Comment by berndbischl** [comment]
closing this, as the ianhowson page seems to work

**Comment by schiffner** [comment]
At the moment we are back to rdocumentation because it's working now again and because inside-r is down...
In the pretty frequent case that we introduce new functions we still might want to build our own documentation, but it's better to open a new clean issue for this.

**Comment by berndbischl** [comment]
> At the moment we are back to rdocumentation because it's working now again and because inside-r is down...
> In the pretty frequent case that we introduce new functions we still might want to build our own documentation, but it's better to open a new clean issue for this.

why dont we use ianhowson? this shows mlr 2.9, while rdocumentation is again outdated at 2.8?

**Comment by schiffner** [comment]
Because the level version of the tutorial has dead links then.

**Comment by berndbischl** [comment]
> Because the level version of the tutorial has dead links then.

? i dont get that

**Comment by schiffner** [comment]
Sorry, I meant "devel version".

What I mean is that we have quite often mismatches between the online docs (like rdocumentation) and the devel version of the tutorial, for example
- if stuff gets renamed like partialPrediction -> PartialDependence, or
- if we add arguments to an existing function, or
- if we have new functions in mlr devel  for which some nice person has already written a tutorial page including the links to the online docs...

It's not high-prio though.

**Comment by berndbischl** [comment]
well my 2 cents on this:

1) all of what you list i think we have to / should simply live with. it is the devel version of the tutorial for a reason. also: if we have faster release cycles, that problem will be much less severe.

2) it sounds that this has nothing to do with rdocumentation vs. ianhowson.
so again: why do we use a service which is continously outdated instead one which seemed to have been automatic uptodate in the past each time i checked?

**Comment by schiffner** [comment]
> 1) all of what you list i think we have to / should simply live with. it is the devel version of the tutorial for a reason. also: if we have faster release cycles, that problem will be much less severe.

Ok.

> 2) it sounds that this has nothing to do with rdocumentation vs. ianhowson.

I never said that.

> so again: why do we use a service which is continously outdated instead one which seemed to have been automatic uptodate in the past each time i checked?
- ianhowson does not have all packages.
- rdocumentation is up-to-date, very, very much improved and has nice things like for example has hyperlinks between doc pages, a console where you can directly run the examples etc.

**Comment by berndbischl** [comment]
> rdocumentation is up-to-date, very, very much improved and has nice things like for example has hyperlinks between doc pages, a console where you can directly run the examples etc.

thx for the clarification ;-) i will trust your (much more informed) judgement here.
close now?

**Comment by schiffner** [comment]
:)
We can easily switch back and forth in case that rdocumentation causes problems again.
