### ISSUE TITLE
Appendix filters: univariate filter

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr-tutorial#32]
IIRC we deprecated this. But it is still visible in the list.
I dont care so much about this, maybe just add the deprecation info in the note?

**Comment by schiffner** [comment]
I can do that, but maybe a cleaner solution is to change `listFilterMethods` (which is used to create the table in the tutorial).

**Comment by berndbischl** [comment]
of course thats much better. lets simply remove it there

**Comment by schiffner** [comment]
I opened a new issue for this in the mlr tracker.

**Comment by schiffner** [comment]
This was fixed by @berndbischl here: https://github.com/mlr-org/mlr/pull/634
`listFilterMethods` shows also deprecated filter methods with deprecation info in the note.
