### ISSUE TITLE
Breaking up Tuning into multiple sections

### ISSUE THREAD

**Issue by masongallo** [mlr-org/mlr-tutorial#42]
@berndbischl and I discussed breaking up the Tuning tutorial and integrating my GSoC work into a basic tuning page. More advanced tuning methods like f-racing etc will go in their own advanced tuning section. I will submit a PR.

**Comment by berndbischl** [comment]
cool. pls do so.

**Comment by schiffner** [comment]
I forgot close this earlier.
Thx again :)
