### ISSUE TITLE
Add examples about train performance

### ISSUE THREAD

**Issue by masongallo** [mlr-org/mlr-tutorial#44]
A few places in the tutorial I think would benefit from having examples showing test/train performance rather than just test. That way students can see an example of eg creating a learning curve showing both test and train performance to evaluate under/over fitting. I'm happy to add these in:
- [x] learning curves
- [x] GSoC hyper parameter effect work (I'm adding this in #43 )
- [x] tuning

Any other suggestions?

**Comment by berndbischl** [comment]
> Any other suggestions?

nope just do it

**Comment by schiffner** [comment]
We have also estimateRelativeOverfitting. Haven't checked it out myself yet, but can maybe mentioned in this regard.

**Comment by masongallo** [comment]
@schiffner wow! I didn't even know that was in the API - I should integrate that

**Comment by berndbischl** [comment]
> We have also estimateRelativeOverfitting. Haven't checked it out myself yet, but can maybe mentioned in this regard.

yeah we really need to mention these things at least briefly. even like 2-3 sentences in the tutorial plus maybe some crosslinks from other sections would help here.

**Comment by schiffner** [comment]
Closing this. Making a clean new issue for estimateRelativeOverfitting
