### ISSUE TITLE
Generate the tutorial as pdf

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#50]
This seems useful
- R packages rmarkdown and bookdown
- https://github.com/mkdocs/mkdocs/issues/374, https://github.com/jgrassler/mkdocs-pandoc
- https://atom.io/packages/markdown-pdf

**Comment by jakob-r** [comment]
Didn't we have this issue once? I still see it complicated for the integrated learners and other stuff from the appendix as we use HTML there and not pure markdown.
Probably we could exclude stuff from the PDF but then again: Why do we need PDF?

My cons
- just anonther thing we have to keep in sync
- we already offer zip for offline usage
- PDFs are really unflexible to the viewing device
- We will write a book about mlr anyhow. That is the moment when we generate a PDF from the tutorial :smile: 

Pros:
- PDF looks more sciency?

**Comment by berndbischl** [comment]
@jakob-r 
the pdf we need so it can be put on arxiv. julia and others put much work into this, so it should be citeable.

**Comment by berndbischl** [comment]
i am labeling this as "red" now :)
this should have top prio so we can cite it.

@larskotthoff  @zmjones  @mllg @jakob-r 

we should all be interested in this, lets help julia here!

**Comment by larskotthoff** [comment]
This doesn't seem to be easy. There's https://github.com/jgrassler/mkdocs-pandoc but that doesn't work with embedded images. There's also a `pandoc()` function in R that allows to create PDFs for each individual page, but that doesn't work either.

**Comment by berndbischl** [comment]
but we really need this! i always thought this was kinda an advantage of mkdocs!

> but that doesn't work with embedded images.

what exactly does this mean?

**Comment by berndbischl** [comment]
i just did 
render("src/impute.Rmd", output_format = "pdf_document")

and it works pretty fine and i get a nice pdf? yes, we will have to to some custom sed prepreprocessing for our linking command in the  docs, but that seems pretty doable?
where is the problem?

**Comment by larskotthoff** [comment]
Pandoc generates LaTeX for PDF output, which then has something like

```
\includegraphics{path/to/somewhere:data<base64encodedImage>}
```

which obviously doesn't compile. Using the way you posted to compile the files individually returned an error for some files. Even if that worked we would have to manually compile a TOC, change page numbers etc.

**Comment by berndbischl** [comment]
1) In general, you are aware that we need a positive constructive solution here?

2)

> Using the way you posted to compile the files individually returned an error for some files

Can you please in cases like these really post the example so we can see whether there is a workaround?

3) 

> Even if that worked we would have to manually compile a TOC, change page numbers etc.

Well, how about we simply leave it out? and where do we use page numbers? 

4) You you have a better alternative suggestion?

**Comment by berndbischl** [comment]
i have now created a subfolder "pdf" with a script. that nearly already generates a PDF for the whole basic part. 

as i am working on the RMD files i dont see why this should not work.

also note: adding a TOC was trivial. 

yes there are a few issues left:
- we need to deal with the custom links
- we need to deal with image paths

and some minor polishings maybe. but to me this really looks solvable.

it should be top prio IMHO to finish this IMHO so we and other can cite this.

**Comment by schiffner** [comment]
I was working on something using bookdown but hadn't time to write everything down I tried.
If you want to take over, Bernd, feel free.

**Comment by larskotthoff** [comment]
Well sorry for trying one of the proposed approaches, finding that it didn't work, and rather than letting somebody else spend effort on this again posting here that it didn't work.

**Comment by mllg** [comment]
> This doesn't seem to be easy. There's https://github.com/jgrassler/mkdocs-pandoc but that doesn't work with embedded images. 

This is something we can easily solve by just **not** using inline images if this is the only issue here.

**Comment by larskotthoff** [comment]
Fixed in #58 with PDF version attached.

**Comment by schiffner** [comment]
Thy very much @larskotthoff for doing this!

**Comment by jakob-r** [comment]
@berndbischl To cite mlr we will soon have the paper, or not?

**Comment by berndbischl** [comment]
> @berndbischl To cite mlr we will soon have the paper, or not?

why do you ask? JMLR takes about 6 weeks to review as far as I know
What their response will be i cannot say, obviously.

**Comment by schiffner** [comment]
I'm closing this here. I opened #64 for the small remaining issues that we can solve over time.
