### ISSUE TITLE
Reproducibility in tutorial

### ISSUE THREAD

**Issue by masongallo** [mlr-org/mlr-tutorial#53]
I think we should have at least a note somewhere reminding users about reproducibility with`set.seed`

**Comment by larskotthoff** [comment]
Sounds good -- maybe in the benchmarks section? Do you want to do a PR for this?

**Comment by masongallo** [comment]
That sounds reasonable. I'll do a PR soon.

**Comment by berndbischl** [comment]
@MasonGallo 
this sounds like adding a short paragraph somewhere. i am also unsure whether this is not more "common basic R knowledge"

but feel free to add a short comment in the benchmark section, but close pls ASAP

**Comment by masongallo** [comment]
@berndbischl 

Yup, less this is how to use `set.seed` and more reminder that it works as expected with mlr.

**Comment by berndbischl** [comment]
of then do it and close :)
