### ISSUE TITLE
the the quickstart page really sucks. should we change it?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr-tutorial#56]
lets collect some ideas here.

**Comment by masongallo** [comment]
I would propose a quick start for various common "tasks" that basically become quick scripts for users to adapt:
- classification with resampling and hyperparam tuning
- regression with resampling and hyperparam tuning
- benchmarking
- clustering
- etc

sklearn sorta does this where if you go on the documentation for a learner, they have "examples" at the bottom of each page [example](http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#examples-using-sklearn-neighbors-kneighborsclassifier)

**Comment by jakob-r** [comment]
Why does it suck?
My proposal: We could have a Quickstart section for every chapter.

**Comment by larskotthoff** [comment]
I like the idea of having a quickstart for every chapter.

**Comment by berndbischl** [comment]
> Why does it suck?

because it is much too short and does not really help you to get into the package.
and some people dont want to spend hours reading our lengthy chapters

> I like the idea of having a quickstart for every chapter.

i dont. and we already had this in the past! turned out it was unmaintenable because it resulted in having each chapter kinda "twice". it also seems to go overboard / is not what the quickstart should be (IMHO).

I like what Mason posted. Some sweet, cool worked out use cases. We don't need a million.
I think eg posting a solution to this would not be bad

https://www.kaggle.com/c/titanic

**Comment by ja-thomas** [comment]
> I think eg posting a solution to this would not be bad
> 
> https://www.kaggle.com/c/titanic

We wanted to do this anyways and post it on the kaggle scripts right?

**Comment by berndbischl** [comment]
> We wanted to do this anyways and post it on the kaggle scripts right?

yes we could do this too, good idea

**Comment by jakob-r** [comment]
So what you want is not a quickstart but a guided use case? IMO The quickstart is intended to give a copy pasta example without statistical / machine learning background. Because when you already have that background you can understand a simple code snippet easily.

But you are right that we had it already kind of like this. But maybe we did it wrong and we are able to do it better now.

**Comment by jakob-r** [comment]
And [bug] is clearly an overstatement.

**Comment by berndbischl** [comment]
> So what you want is not a quickstart but a guided use case? IMO The quickstart is intended to give a copy pasta example without statistical / machine learning background. Because when you already have that background you can understand a simple code snippet easily.
> 
> But you are right that we had it already kind of like this. But maybe we did it wrong and we are able to do it better now.

the quickstart is supposed to give a quick, hands on introduction to get into the package. 
usecases seem to be best for this. 

i really dont want a quickstart for each chapter.
who is going to write this? the tutorial does not even cover the complete list of of topic for now. 

and mixing a few different things together in a nice usecase quickstart is really what we are missing.  
"here is a fully worked out example. we will not talk about every option and detail. for thta, pls look at the tutorial and the API docs"

**Comment by schiffner** [comment]
The quick start section on the index page has been updated. (#85)
Other quick start pages are in progress. (#90, #86 )

**Comment by SteveBronder** [comment]
> i really dont want a quickstart for each chapter.

I think a good compromise is, take all the code for the tutorial section and place it at the bottom. That way people can copy-paste and see how the whole thing works together.

**Comment by SteveBronder** [comment]
> and mixing a few different things together in a nice usecase quickstart is really what we are missing.
"here is a fully worked out example. we will not talk about every option and detail. for thta, pls look at the tutorial and the API docs"

Bernd would this be sort of what you are looking for? I would have to add the code directly into the analysis and remove a few things that were relevant for that specific project.

It does imputation, tuning, stacking, and makes some pretty graphs for the output 

https://github.com/Stevo15025/hedgeable_ads

**Comment by berndbischl** [comment]
> I think a good compromise is, take all the code for the tutorial section and place it at the bottom. That way people can copy-paste and see how the whole thing works together.

good idea. open issue for this?

**Comment by berndbischl** [comment]
> Bernd would this be sort of what you are looking for? I would have to add the code directly into the analysis and remove a few things that were relevant for that specific project

that's a tad more complex than what i thought of, and i also think we should have simpler use cases. but yes, this is definitely cool. if included there should also be a at least a teaser blog post linking to it, or you put it in the tutorial and also the blog.

**Comment by SteveBronder** [comment]
The blog is a much better place for something more compicated like that. I'll do this on Monday

**Comment by berndbischl** [comment]
> the blog is a much better place for something more compicated like that. I'll do this on Monday

well the use cases should be in the tutorial too.
shall we just have a "use case page" in the tutorial with titles and then links to the blog posts?

**Comment by SteveBronder** [comment]
> shall we just have a "use case page" in the tutorial with titles and then links to the blog posts?

Once we have quite a few serious use cases we should do this

**Comment by pat-s** [comment]
This issue was moved to mlr-org/mlr#2322
