### ISSUE TITLE
(Re)Structuring the tutorial?

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#6]
The Advanced section in the tutorial is getting a little full and maybe unclear/confusing.

Tutorial pages to come are:
- more about visualization
- nested resampling
- threshold setting/tuning
- multilabel classification

In Advanced there are some general topics like preprocessing, model selection, ensemble learning, but also some pages purely about classification and some about visualization.

What do you think?  
- Leave everything as it is now
- Build better navigation/clearer structure within section Advanced? (Unfortunately, mkdocs does only allow two levels of navigation, which we already have.)
- Single out Visualization and/or Classification?  
  Cons: destroys the clear structure of the upper navigation bar
  Pro: Particularly info about visualization is scattered at the moment and may be easier to find when collected in one place.

**Comment by zmjones** [comment]
One way around the nav bar issue would be to change the index page to be more of a table of contents. Can we do that with mkdocs?

Do we have anything about stacked learners? That is one thing I think would be nice to have. Caret only recently has this capability via an add-on package.

**Comment by schiffner** [comment]
> One way around the nav bar issue would be to change the index page to be more of a table of contents. Can we do that with mkdocs?

I have to read up on the details. But I remember that there is a toc extension for python markdown.

> Do we have anything about stacked learners? That is one thing I think would be nice to have. Caret only recently has this capability via an add-on package.

In mlr: Yes  
In the tutorial: Unfortunately not yet. The plan was to extend the bagging page (which is quite old), mention/show stacking and call it something like 'Ensemble Methods'.

**Comment by larskotthoff** [comment]
I'm fine with the structure as it is at the moment given the mkdocs restrictions. In general another option would be to make the existing pages longer, e.g. have one page on classification that deals with cost-sensitive and imbalanced classification, and rely more on the section headings and the left-hand navigation.

**Comment by berndbischl** [comment]
For me the structure that we currently have is also OK, although there are certainly some improvements possible.

Eg We could try to order things a bit better in "advanced". One option to group better might be to put a group name before the entry in the menu. Like
Visualization: Partial Dep Plots
Visualization: Another Plot

**Comment by berndbischl** [comment]
> Do we have anything about stacked learners?

It is pretty stupid that we do not advertise and explain this better. Quite a lot of people are interested inthis.

**Comment by schiffner** [comment]
Thank you all for your replies.

I found out last week that more than two levels of navigation are supported for the mkdocs theme that we use (the docs on this are just outdated)
https://groups.google.com/forum/#!topic/mkdocs/rU73ZC1BKis

I guess we could use this to order things a bit better in Advanced.

Here are screenshots how this would look like:
https://github.com/mkdocs/mkdocs/pull/482

To make this work all code chunks regarding `.dropdown-submenu` need to be included in `custom_theme/base.css`:
https://github.com/mkdocs/mkdocs/commit/7849e71b8401608f86e81b48e7b29d18e8408663

**Comment by jakob-r** [comment]
I will try to put the custom mlr css changes into an extra file so that we can just always update `base.css`

**Comment by schiffner** [comment]
Thanks @jakob-r ! That's much better than my proposal.
