### ISSUE TITLE
Small fixes for tutorial pdf

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#64]
I retrieved this from #58.

Small issues:
- [ ] Broken links to Appendices
- [ ] Overflowing output in code chunks
- [ ] Code indentation seems to be 4 spaces if lines are broken automatically
- [x] Tables (e.g in Visualization section): possible solutions:
    change the formatting, must all these tables be tables?
- [ ] Headers?
- [ ] Language fits a web page and not a pdf
- [ ] Explanations and plots are sometimes far apart?
- [ ] abstract
- [ ] list of references

**Comment by jakob-r** [comment]
@schiffner Can you tell why it was necessary to separate the caching? This doubles the runtime on travis - and at the moment leads to timeouts.

**Comment by schiffner** [comment]
> @schiffner Can you tell why it was necessary to separate the caching? This doubles the runtime on travis - and at the moment leads to timeouts.

I'm not sure, if I remember correctly this was the easiest solution due to problems with embedded images (?). See the discussion in #50 for details.

**Comment by jakob-r** [comment]
Hmm... then I just might try to undo this and see what happens.
