### ISSUE TITLE
Show how to do hyperparameter effects plots for >= 3 hyperpars

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#66]
The corresponding PR https://github.com/mlr-org/mlr/pull/1233 already has a description and an example, which can be used.

See https://github.com/mlr-org/mlr/issues/1281

**Comment by schiffner** [comment]
@MasonGallo: I shamelessly scavenged your example from mlr-org/mlr#1281. Feel free to change/correct anything.

I also gave you write access to this repo. Sorry, forgot to do this earlier.

**Comment by masongallo** [comment]
Thanks! I think this is fine for now. Finding a more "interesting" dataset for the examples is on my long term todo list.

**Comment by schiffner** [comment]
Ok, great. I will close this here then.
