### ISSUE TITLE
Extend section: Add more info for developers

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#67]
- where to find the relevant source code?
  (see https://github.com/mlr-org/mlr/issues/1276)
- where to find the tests?
- relevant background info to understand tests: e.g. what's the mlr.debug.seed?
- guidelines for tests: e.g. make sure that all learner interfaces are running with default configuration
- info about (internal) helper functions
- [x] learners
- [ ] filters
- [ ] measures
- [ ] imputation

**Comment by larskotthoff** [comment]
Yes, sounds good! Do you want to take care of this?

**Comment by schiffner** [comment]
Sorry for not responding sooner. I meant to work on this issue today, but was driven crazy by the gbm stuff.
I certainly don't mind any help. :) So if you have time and want to go ahead...

**Comment by pat-s** [comment]
I'll check in detail in the near future if the current information is enough for developers. 
We should definitely link it more prominently in the README as this is the first place where new people will look for developer instructions.

**Comment by pat-s** [comment]
This issue was moved to mlr-org/mlr#2320
