### ISSUE TITLE
Typo in chapter Classifier Calibration

### ISSUE THREAD

**Issue by rwarnung** [mlr-org/mlr-tutorial#74]
Hi, in the named chapter it says 

> learners must be constructed with predict.type = TRUE

shouldn't this be 

> learners must be constructed with predict.type = "probability"

?
I just thought this was a typo.
Best regards,
RW

**Comment by schiffner** [comment]
Hi Richard,

thanks very much for spotting the typo. I have fixed it.

Best,
Julia
