### ISSUE TITLE
Error when compiling bagging tutorial

### ISSUE THREAD

**Issue by SteveBronder** [mlr-org/mlr-tutorial#75]
Getting this error when doing `./build`

```
./build
# Loading required packages ...
# Building PDF version...
# Knitting file 'advanced_tune.Rmd' ...
# Knitting file 'bagging.Rmd' ...
# Quitting from lines 64-71 () 
# Error in train.default(learner = bag.lrn, task = bh.task, subset = train.inds) : 
#   argument "y" is missing, with no default
# Calls: lapply ... withVisible -> eval -> eval -> train -> train.default
# Execution halted
```

**Comment by larskotthoff** [comment]
Do you have the latest versions of all packages? We build the tutorial on Travis after mlr commits, so we should notice immediately if it's broken.

**Comment by SteveBronder** [comment]
My computer says I do, but from yesterday we know that this whole rig is buggy.

Just to confirm, if I make a new branch in mlr-tutorial that won't mess up anything? It will just contain the new stuff for forecasting and then I can try it on my laptop

**Comment by larskotthoff** [comment]
That'll be fine.

**Comment by SteveBronder** [comment]
Could I get permissions to push? I'm getting an access denied error

**Comment by larskotthoff** [comment]
Should work now.

**Comment by SteveBronder** [comment]
Works on my laptop. Dunno why my desktop bugs out so much
