### ISSUE TITLE
Add info about mlr configuration to benchmark page

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#80]
We should add some rudimentary info about configuration (and a link to the configure mlr page) to the benchmark page.

Particularly important options for benchmark experiments are
* `on.learner.error`
* `on.measure.not.applicable`

Also relevant are:
* `show.info`
* `show.learner.output`

**Comment by pat-s** [comment]
This issue was moved to mlr-org/mlr#2317
