### ISSUE TITLE
Split the preprocessing page?

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#84]
As the preprocessing page is getting a little long, one could split it:
* keep the info about built-in wrappers (create dummy features, remove constant features, caret) on the preprocessing page
* move the info about writing a custom preproc wrapper to a new page in the Extend part of the tutorial.

(effort-hardfix is maybe misleading. It's not really hard to do, but potentially affects several other tutorial pages, where text and links have to be adjusted, so some reading and thinking is required.)

**Comment by pat-s** [comment]
This issue was moved to mlr-org/mlr#2313
