### ISSUE TITLE
mlr tutorial is broken

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr-tutorial#9]
because of timeout, and mlr changes
-- Fork from Issue #2

**Comment by schiffner** [comment]
I opened a separate issue for the timeout.

https://github.com/mlr-org/mlr-tutorial/issues/10

**Comment by larskotthoff** [comment]
Depends on berndbischl/mlr#367.

**Comment by larskotthoff** [comment]
Fixed now.
