### ISSUE TITLE
finish cheatsheet

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr-tutorial#94]

**Comment by schiffner** [comment]
https://github.com/mlr-org/mlr-tutorial/tree/cheatsheet

**Comment by SteveBronder** [comment]
Any update on this?

**Comment by SteveBronder** [comment]
From the cheat sheet:
https://github.com/mlr-org/mlr-tutorial/blob/cheatsheet/cheatsheet/MlrCheatsheet.pdf

If there is not much left to do for the cheatsheet, that extra whitespace on the second page could instead be used for the graphs. So we can move the visualization and plots sections to the second page and enlarge them a bit
