### ISSUE TITLE
quickstart: must really include a few more operations

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr-tutorial#98]
at LEAST show resampling in 3 lines.

maybe simple even tuning.

**Comment by masongallo** [comment]
There is also a warning in the code:
```#> Warning in lda.default(x, grouping, ...): group virginica is empty```

I will see about writing up something really quick this week.

**Comment by schiffner** [comment]
Thanks very much.
The warning was my fault, really dumb typo. It's fixed now.

**Comment by pat-s** [comment]
This issue was moved to mlr-org/mlr#2308
